// legacy-angular/src/app/splash/splash.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-splash',
  templateUrl: './splash.component.html',
  styleUrls: ['./splash.component.css'],
  imports: [CommonModule]
})
export class SplashComponent implements OnInit {
  showSplash?: Boolean;
  showGif?: Boolean;
  showVideo?: Boolean;
  selectedImagePath?: string;
  selectedVideoPath?: string;


  constructor() { }

  ngOnInit(): void {
    let expire = new Date("2024-12-15T00:00:00");
    let today = new Date();
    this.showGif = true;
    this.showVideo = false;

    if (today >= expire) {
      this.showSplash = false;
    } else {
      this.showSplash = true;

      let startShowingSplash = new Date("2022-08-01T00:00:00");
      if (today >= startShowingSplash) {

        // let paths: string[] = Array.from(Array(12)).map((x, i) => {
        // return "t-" + i + ".gif";
        // });

        let paths: string[] = ['hamfood.webp', 'turkhat.webp', 'turktrot.webp', 'wolfslice.webp'];
        let selectedIndex = this.getRandomFromRange(0, paths.length - 1);
        if (paths[selectedIndex].includes("gif") || paths[selectedIndex].includes("webp") || paths[selectedIndex].includes("jpg") || paths[selectedIndex].includes("jpeg")) {
          this.selectedImagePath = `/assets/images/${paths[selectedIndex]}`;
          this.showGif = true;
          this.showVideo = false;
        } else {
          this.selectedVideoPath = `/assets/video/${paths[selectedIndex]}`;
          this.showVideo = true;
          this.showGif = false;
        }
      }
    }

    setTimeout(() => {
      this.showSplash = false;
    }, 11000);
  }

  getRandomFromRange(min: number, max: number): number {
    return Math.floor(Math.random() * (max - min + 1) + min);
  }

}

<div class="splash" *ngIf="showSplash">
  <img *ngIf="showGif" src={{selectedImagePath}} />
  <video *ngIf="showVideo" controls loop muted autoplay oncanplay="this.play()" onloadedmetadata="this.muted = true">
    <source src="{{selectedVideoPath}}" type="video/mp4" />
    Browser not supported
  </video>
</div>

// src/components/Splash.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	let showSplash = $state(false);
	let showGif = $state(true);
	let showVideo = $state(false);
	let selectedImagePath = $state('');
	let selectedVideoPath = $state('');

	function getRandomFromRange(min: number, max: number): number {
		return Math.floor(Math.random() * (max - min + 1) + min);
	}

	onMount(() => {
		const expire = new Date('2024-12-15T00:00:00');
		const today = new Date();

		if (today >= expire) {
			showSplash = false;
			return;
		}

		showSplash = true;

		const paths: string[] = ['hamfood.webp', 'turkhat.webp', 'turktrot.webp', 'wolfslice.webp'];
		const selectedIndex = getRandomFromRange(0, paths.length - 1);
		const selected = paths[selectedIndex];

		if (selected.endsWith('.gif') || selected.endsWith('.webp') || selected.endsWith('.jpg') || selected.endsWith('.jpeg')) {
			selectedImagePath = `/assets/images/${selected}`;
			showGif = true;
			showVideo = false;
		} else {
			selectedVideoPath = `/assets/video/${selected}`;
			showVideo = true;
			showGif = false;
		}

		setTimeout(() => {
			showSplash = false;
		}, 11000);
	});
</script>

{#if showSplash}
	<div class="fixed inset-0 z-50 flex items-center justify-center bg-black/80">
		{#if showGif && selectedImagePath}
			<img src={selectedImagePath} alt="splash" class="max-h-screen max-w-screen object-contain" />
		{:else if showVideo && selectedVideoPath}
			<video src={selectedVideoPath} autoplay muted class="max-h-screen max-w-screen object-contain"></video>
		{/if}
	</div>
{/if}
